### ISSUE TITLE
Hard dependency on Angular demo module in compiled dell-ui-components.js

### ISSUE THREAD

**Issue by mredding10** [DellGDC/dell-ui-components#1]
There's a hard dependency on a demo module in the compiled dell-ui-components.js (dist/dell-ui-components/dell-ui-components.js) that is causing issues with Angular injection. When lines 4592-4612 are removed from this file [adding a filter to the demo module on _.str], everything works fine and compile.

With these lines included, dell-ui-components can't be included without also including demo.js, which creates a circular dependency tree (demo.js requires dellUiComponents, but dellUiComponents required demo, etc).

**Comment by bolora** [comment]
The culprit is line 70 of the index file that is used in the build process
<script src="demo-assets/filters/_.str.js" data-concat="dellUiComponentsJs"></script>
it is supposed to be assigned to "demoJs"
I'll fix asap

**Comment by bolora** [comment]
new tag was pushed out, you can update your package and is should be fine now.  Nice catch, thanks
